# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-12-14 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0007_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userAccount', models.CharField(max_length=20)),
                ('productid', models.CharField(max_length=20)),
                ('productnum', models.IntegerField()),
                ('totalprice', models.FloatField()),
                ('ischose', models.BooleanField(default=True)),
                ('productimg', models.CharField(max_length=150)),
                ('productlongname', models.CharField(max_length=150)),
                ('orderid', models.CharField(default='0', max_length=20)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
    ]
