# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-12-16 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0008_carts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=20)),
                ('userid', models.CharField(max_length=20)),
                ('progress', models.IntegerField()),
            ],
        ),
        migrations.AlterModelManagers(
            name='carts',
            managers=[
                ('object1', django.db.models.manager.Manager()),
            ],
        ),
    ]
