# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-02-24 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0009_auto_20181216_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_d',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_num', models.CharField(max_length=128)),
                ('d_status', models.IntegerField(default=0)),
                ('d_create', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axf.User')),
            ],
        ),
        migrations.CreateModel(
            name='Order_d_Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_num', models.IntegerField(default=0)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axf.Goods')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axf.Order_d')),
            ],
        ),
    ]
