# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-02-25 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0010_order_d_order_d_goods'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_d',
            name='is_select',
            field=models.BooleanField(default=True),
        ),
    ]
